---
- name: obtain list of swap images
  shell: "cat /proc/swaps | grep .img | awk '{print $1}'"
  changed_when: False
  register: isset_swapoff_images

- name: when swap is present
  block:
    - debug:
        var: isset_swapoff_images

    - debug:
        var: isset_swapoff_images.stdout_lines

    - name: disable swap
      command: swapoff -a

    - name: remove swap image
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ set_swapoff_images.stdout_lines }}"

    - name: disable swap in fstab
      mount:
        path: "{{ item }}"
        state: absent
      loop: "{{ set_swapoff_images.stdout_lines }}"
  when:
    - isset_swapoff_images.stdout_lines | length > 0
